// Generated by https://quicktype.io
class Clients {
  List<Client> items = new List();

  Clients();

  //Agregar cada cliente recuperado del json a la lista
  Clients.fromJsonList (List<dynamic> jsonList){
    if(jsonList == null) return;
    for (var item in jsonList){
      final client = new Client.fromJson(item);
      items.add(client);
    }
  }

}

// Clase Cliente
class Client {
  int id;
  String name;
  String email;
  String phone;
  String function;
  String commercialCompanyName;
  String street;
  String zip;
  String city;
  String pais;
  String writeDate;

  //Constructor
  Client({
    this.id,
    this.name,
    this.email,
    this.phone,
    this.function,
    this.commercialCompanyName,
    this.street,
    this.zip,
    this.city,
    this.pais,
    this.writeDate,
  });

  Client.m({
    this.id,
    this.name,
    this.email
  });
  
  //Mapear cliente desde la API 
  Client.fromJson (Map<String, dynamic> json){
    id                    = json['id']; 
    name                  = json['name']; 
    email                 = json['email'] ;
    phone                 = json['phone']   ;
    function              = json['function'] ;
    commercialCompanyName = json['commercial_company_name'] ;
    street                = json['street'] ;
    zip                   = json['zip'] ;
    city                  = json['city'] ;
    pais                  = json['pais'] ;
    writeDate             = json['write_date'];
  }
}


